### PR TITLE
Update layout, parse args and other things

### PR DESCRIPTION
**Pull request by vsc55**
Hi @billsimon,

I have made some small updates to the module to see what you think.

- do not allow to load views files if it is not freepbx that loads them.
- create floating menu for action buttons (add new number, settings, list).
- add option to be able to reload the list of numbers without reloading the whole page.
- modify updateProviders so that it creates the provider if it does not exist, otherwise it gives an SQL error.
- remove symbolic link for the public foler in process uninstall.
- add info installation process.
- extract html code from userman showpage to view file.
- parameterize table names.
- auto generate the settings.php form with the data from the provider-*.php.
- show error message when trying to add a did as new that already exists.
- delete table smsconnector_providers, now it is stored in kvstore and allows us to create all the settings we need without modifying the tables.
- refactor.

imagen

imagen

imagen

### CODE REVIEW

**Comment by billsimon** [comment]
Hi,

There are some nice updates here and I really appreciate the contribution.

Unfortunately the sending function no longer works. Can you go back and review the logic? The problem seems to be with Smsconnector->getProvider() method but I have not been able to successfully debug.

**Comment by vsc55** [comment]
Hi @billsimon,
I have already found the error.
As soon as I have it ready I update the PR.

**Comment by vsc55** [comment]
Hi @billsimon,
With the latest fix it should now work without problems.

**Comment by billsimon** [comment]
I merged your work to the `master` branch. Thank you! I am going to do a little more work before merging to release branch.

**Pull request closed without merging**
